### ISSUE TITLE
2160p (4K) & 1080p (Full HD) not playing smoothly

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#100]
The xiaomi mi5 have Qualcomm snapdragon 820 chipset which is capable of playing , decoding,encoding 2160p@30fps
1080p@30fps
720p@120fps

But in this rom these video not playing smoothly

Affectes Version & Device

ROM Version =

1] [JDCTeam][7.1.1][12 March] 20170312- Stable 2.
2] [JDCTeam][7.1.1][28 March][Substratum][EAS] - Stable 3

Device = Xiaomi Mi5

**Comment by B--B** [comment]
This report is invalid (and not reproducible, at least by me) provide the requested info for a bug report

**Comment by B--B** [comment]
No info provided after a month, closed.
