### ISSUE TITLE
Phone lags during Clash of Clans Game Play

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#101]
When we play the game clash of clans the game lags & slow down in attack session

Affectes Version & Device

ROM Version =

1] [JDCTeam][7.1.1][12 March] 20170312- Stable 2.
2] [JDCTeam][7.1.1][28 March][Substratum][EAS] - Stable 3

Device = Xiaomi Mi5

**Comment by B--B** [comment]
This report is invalid, provide the requested info for a bug report

**Comment by B--B** [comment]
No info provided after a month, closed.
