### ISSUE TITLE
Bluetooth crash with stock kernel

### ISSUE THREAD

**Issue by carminebianco** [AOSP-JF-MM/issue_tracking_aosp#103]

**Comment by B--B** [comment]
It's not a bug, if you want a working bt you must compile the ROM by yourself reverting this: https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/commit/e6bb7bd4d6d74bb5115fbb2aa59ce31a6c858ec5 

Ps: next time you open a bug report please follow our guidelines, thanks
