### ISSUE TITLE
Build - Add devices specific repos dependencies

### ISSUE THREAD

**Issue by B--B** [AOSP-JF-MM/issue_tracking_aosp#107]
I'm writing here so everyone can read, we should really implement device specific repos dependencies, we added new devices to build barrier (and hopefully we will add more devices soon), this will add more and more repos to our build enviroment, and will require everytime more space on our ssd for unuseful repos, and more time for repo sync. Honestly i never cared about this until now because we were bulding only for a few devices, so i don't know how other ROMs implemented this function :) if someone already took a look at it feel free to merge everything in our repos, otherwise i will take a look hopefully this weekend, sorry but real life comes first :)

**Comment by smeroni68** [comment]
A way to solve has been already proposed from MZO:

https://github.com/AOSP-JF-MM/platform_manifest/commit/587a48d1a0f6e432ca5cdabb9123950a02303aaf#commitcomment-22130344

Need to check if it's fine.

**Comment by xlxfoxxlx** [comment]
roomservice could be implemented, you just have a dependencies file in device tree and then when you lunch the device, it fetches only needed device repos.

**Comment by smeroni68** [comment]
Welcome Fox.

**Comment by B--B** [comment]
Tested a working on Mi5 and Jf, other devices may need some small change but roomservice is working pretty fine. Additional repos can be added to dependencies (like device specific HALs) but we can move them later.
