### ISSUE TITLE
severe battery drain

### ISSUE THREAD

**Issue by pnutts** [AOSP-JF-MM/issue_tracking_aosp#111]
with latest update ( updated July 2 /17 ROM 20170624 ) I have notice severe battery drain when on standby with S4 i337M phone running nougat 7.1.2. Never happened before.

**Comment by smeroni68** [comment]
After two weeks from releasing? When you installed it?

**Comment by pnutts** [comment]
I installed it on July 2/17 thru OTA update.
I have reverted back to earlier build for now.
Will wait until a newer build is released.

**Comment by smeroni68** [comment]
Rom has no battery drain itself. It's something related to your installation. For your information, user that download the build are 4068 right now... and we do not see on xda the thread full of posts about severe battery drain.
Wait for next build, but as wrote, is not rom dependent.

**Comment by pnutts** [comment]
I still will wait for next build and do it manually - not OTA update.
No battery drain problem with previous build since re-install.

**Comment by B--B** [comment]
No one reported battery drain after our latest public release, so I assume it's fixed
