### ISSUE TITLE
7.1.2 AOSP NJH47B - GPS Issues

### ISSUE THREAD

**Issue by RuKaDa** [AOSP-JF-MM/issue_tracking_aosp#112]
Performed a clean install, latest modem and bootloader is installed. Everything is working fine with this ROM (BTW its awesome, thanks to developers). The only issue is regarding with the GPS, it can only fix if the airplane mode is turned ON. When turned OFF i can´t get any kind of fix, tried with all the possible combinations that i´ve remember Wifi, mobile data, BT, only GPS, high accuracy and so on. Nothing seems to get a fix. Please find the attached log, hope that helps to find it.

Best Regards to all

[2017-07-10-20-57-08.zip](https://github.com/AOSP-JF-MM/issue_tracking_aosp/files/1136951/2017-07-10-20-57-08.zip)

**Comment by smeroni68** [comment]
When was last time you get a fix with the rom?

**Comment by RuKaDa** [comment]
About 15 minutes before my previous post, with airplane mode turned ON, if i set it to OFF the GPS fix is like a beacon, on for a few seconds and off, and it keeps this way.

**Comment by smeroni68** [comment]
Did you use any app to check the GPS position?

**Comment by RuKaDa** [comment]
I´ve tried GPS status & Toolbox, Faster GPS, both have found at least 15 satellites, although when using navigation app (tried Sygic, iGO and Meo Drive) i cant get a fix. Can i ask you if you find something wrong in the log file?

**Comment by smeroni68** [comment]
I haven't checked yet... but in the mean time I went out of my house and switched on the GPS and app (Status GPS)... it took around 20 seconds:

https://www.dropbox.com/s/gnqlvdcr9erfyv1/Screenshot_20170710-223645_clear.png?dl=0

No tricks, just switched on as High accuracy and updated agps data...

Tested with Google maps and waze too... apps get the fix in few seconds.

**Comment by RuKaDa** [comment]
With Status GPS i´ve also had a fix, really fast fix btw, but with navigation apps it doesn´t work. I´ll try it again with Status GPS, with GPS only, i don´t have much mobile data, sorry for that. Back in a few minutes.

**Comment by smeroni68** [comment]
You wrote you installed latest FW... version? On public release you must use maximum version 7.6.8... 7.7.6 is not correct (if you installed)... check if any difference.
Anyway, if you get the fix on Status GPS, I don't see any reason why apps that use the same data get no fix...

**Comment by RuKaDa** [comment]
Latest Stock ROM from updato, rooted with chainfire root, installed twrp and after a few days digging around XDA found this and install it

**Comment by smeroni68** [comment]
So you do not know exactly the fw version?

**Comment by smeroni68** [comment]
You can get from here

https://forum.xda-developers.com/mi-5/development/tool-flashable-firmware-twrp-easy-t3474898

the version 7.5.4 and flash in twrp.

**Comment by smeroni68** [comment]
Just a question: have you wiped the phone completely before installing custom roms? Or let's say better: have you formatted the internal sd (loosing everything on the phone)?

**Comment by smeroni68** [comment]
I'm having a look into the log. But I see some errors app related:

07-10 20:54:07.776 E/navngo  (17725): Config:find_libEGL:egl.cfg not found
07-10 20:54:07.776 E/navngo  (17725): java.io.FileNotFoundException: /system/lib/egl/egl.cfg (No such file or directory)
07-10 20:54:07.776 E/navngo  (17725): 	at java.io.FileInputStream.open(Native Method)
07-10 20:54:07.776 E/navngo  (17725): 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
07-10 20:54:07.776 E/navngo  (17725): 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.utils.StreamUtility.readFile(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.Config.find_libEGL(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.NNG.setParams(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.NNG.reInit(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.NNG.<clinit>(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): 	at com.navngo.igo.javaclient.IgoActivity$5.run(Unknown Source)
07-10 20:54:07.776 E/navngo  (17725): Config:find_libEGL: better then nothing: /system/lib/egl/libGLES_android.so

Seems the app is searching some graphic libraries in the wrong place... not sure, but seems so.

Following log lines, is reported a crash... and many other errors.

But does the app start or force close?

**Comment by RuKaDa** [comment]
Yes, fully wiped, without sdcard, just went outside and got a fix of 4 of 20, but with the beacon style again. Installed this one: I9505XXUHPK2_I9505TPHHPL1_I9505XXUHPK2_HOME.tar.md5, then followed instructions for install AOSP 7.1.2

**Comment by smeroni68** [comment]
Oops... you are on S4 I9505... not on MI5... forgot all stuff about firmware!!

I cleaned the messages here to avoid misunderstanding. But please, remember to post witch model are you on!!

**Comment by RuKaDa** [comment]
yes i noticed that, I9505 it´s my phone, but that´s fine :). So i believe that i made it the right way, starting point: I9505XXUHPK2_I9505TPHHPL1_I9505XXUHPK2_HOME.tar.md5, then rooted with chainfire and installed twrp. After that fully wiped storage (without sdcard) and installed AOSP

**Comment by smeroni68** [comment]
Yes. But is iGo app starting and working? From the log i see a lot of errors on graphic library side...

Have you try using waze or Google maps to see if they get the gps fix?

**Comment by RuKaDa** [comment]
Yes, all the navigation apps that i´ve tried are working and they get a fix but after a few seconds they loose it.

**Comment by smeroni68** [comment]
Have you restored the app from a titanium backup done on previous stock rom? (or something similar)

**Comment by smeroni68** [comment]
Probably (i can assume) you are having a loosing of signal from antenna contacts... it's a known issue on S4...

https://www.youtube.com/watch?v=kMNb8BVr540

Check here and search on youtube (google for "youtube s4 gps antenna contacts")

**Comment by RuKaDa** [comment]
It could be, but with stock rom it doesn´t happen. No restored app, made a fresh and clean install of all apps that i´ve tried. There´s also a user who reported issues with gps with stable 5 but i´m on stable 7 if that could help.

**Comment by RuKaDa** [comment]
Let me go outside again, just to check if i get a fix with status gps, back in 2 minutes

**Comment by smeroni68** [comment]
Sorry, but looking on the log it seems the app itself has a lot of errors on library... and sincerely, due to the fact that S4 with the "age" is giving also this kind of faults... If you wanna be sure, reinstall stock rom and test. Can't help more about this matter.

**Comment by RuKaDa** [comment]
Ok, thanks for your help, just got a 5 out of 18 fix with clear sky, GPS only mode, with airplane mode OFF and ON, do you think that the SIM CARD could eventually be a problem?!

**Comment by smeroni68** [comment]
Really never heard about the sim card can generate this kind of instability.

**Comment by RuKaDa** [comment]
I´ve read about it, because of the APN settings for data. Anyway maybe i´ll try with another AOSP ROM, maybe MM, can you point me one as clean as this?!

**Comment by smeroni68** [comment]
On S4 I know only JDCTeam roms... but you must reinstall stock rom to test. If I'm right, you will have similar problems. Defects do not advise... they happens... and you must know.

**Comment by dkati** [comment]
Please try stock kernel and report back 

Alucard kernel seems to have a strange issue with qmuxd. Happens on optcm sometimes too

**Comment by RuKaDa** [comment]
Hi to all,

Just to give some feedback about the GPS issue in this ROM...

Flashed Official Stock ROM LL 5.0.1 from Sammobile, GPS issues are gone, got a fix of 10 satellites in about 12 seconds, in a cold start it takes 20 seconds to get a fix, performed all these tests with GPS only mode, no wifi and no mobile data, with Airplane mode turned ON and OFF. Also got a 5 satellites fix indoor... Outdoors, the minimum that i´ve got was 6.

With Stable 7 i only get a fix with Airplane mode ON, so i assume that isn´t an hardware issue with my device, and there´s no problem with the GPS antenna also, there´s something that isn´t working with this Stable 7, at least for me, and without being able to use GPS only it doesn´t fit my needs... Too bad because imho this is still an amazing ROM, and despite all the things that didn´t work out well for me, congrats to the developers, testers, and all that somehow where involved on this...

Brgds to all

**Comment by B--B** [comment]
I' ve tried now with both my jf devices and GPS lock works fine, tested with/without GAPPS/SIM/Airplane mode, i remember that some people experienced similar GPS issues in different custom ROMs, for a lot of them the fix was to flash a stock ROM, do a GPS fix and then flash again the custom ROM, even if honestly i don't know why this fixes the GPS lock, and why sometimes it doesn't work properly after a custom ROM flash. We should release soon the new build, if you have time please flash it and let me know if GPS works, if it's still broken please provide me logcat, dmesg and radio logs with the GPS fix in Airplane Mode ON and OFF so i can take a look at it :)

@dkati you should take a look at your Ramdisk if you experience strange issues, as no one reported problems related to QMUXD here , if for some reason QMUXD crashes you should have an unknown baseband and RIL stop working, this is not the case for what i read

**Comment by RuKaDa** [comment]
@B--B Thanks for spending time testing and for your reply, when released i´ll give it a try for sure, let me ask you if the modem and bootloader versions can make the difference or can they somehow related to my GPS issues? Currently my modem and bootloader version is  XXUHQC1, i believe is the latest available in XDA.

**Comment by RuKaDa** [comment]
@B--B and @smeroni68 

I think that i might have found a temporary solution for my GPS issues, on my way work this morning i've started my navigation app, no GPS fix again. As i was jammed in the traffic i've made a s[U]oft restart with location on device only turned ON[/U], after the restart got a GPS fix almost instantaneously, and my navigation app "drive me" to work, during this morning i've made some tests:

If i disconnect the location after a while, there's no GPS fix again.
Soft restart with location on device only ON and GPS fix in a few seconds. :good:
Despite this is not a permanent fix, this solution for me is acceptable, and i hope it works every time i need it and also works for those who having GPS issues :D

Perhaps this is related to power management, i will perform some more tests with the performance profile and automatic optimization changes, just to check if the system keeps the location on.

Thanks for your patience and for trying to help me to get this working, best regards.

**Comment by dkati** [comment]
@B--B there are some situations where qmuxd never shuts down even on airplane mode.i reproduced it while the logcat was disabled via STweaks.never understood why that is being happent. 
talking with mattia,he confirmed it and said its an old bug of alu kernel

**Comment by B--B** [comment]
@dkati QMUXD should never stop, even in airplane mode, no matter what kernel you use. 

https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/blob/aosp-7.1.2/rootdir/etc/init.qcom.rc#L446

It starts here like all other main class services and never stops

You can see by yourself checking logcat and radio log with airplane mode on
