### ISSUE TITLE
Missed some commits for fingerprint wakeup - Mi 5

### ISSUE THREAD

**Issue by etrnal70** [AOSP-JF-MM/issue_tracking_aosp#113]
I've ever seen someone asked about this, but he maybe didn't state this issue clearly. AFter tracking down your xiaomi msm8996 device tree, you missed this 2 commits to prevent accidental fingerprint wake up with proximity sensor.

https://review.lineageos.org/#/q/topic:gemini-pocketmode_improvements+(status:open+OR+status:merged)

I hope you can add it. Thanks guys !

**Comment by B--B** [comment]
https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/afe674b54d52be3bf7274d169182025be3c9208d
https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/dae00ca0f9a9481da99edeeaeb0aad474cd37fb0
https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/1fc16660686711ef5027d747b701206924f0b030
https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/5944376eb0f5c5ba5da7589422660b4b8c778ed4
https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/02fc8dc93751d96ce64b18f82c77970f0543e37d

Merged all missing changes, manually tested on my device and works fine, pocketmode works as expected when the option is enabled, thanks for the report
