### ISSUE TITLE
kernel is not seandroid enforcing set warranty

### ISSUE THREAD

**Issue by Zhaarr** [AOSP-JF-MM/issue_tracking_aosp#114]
Hi,

After installing the rom, phone displays the message below on start up

"kernel is not seandroid enforcing set warranty"

I dont know how to get rid of it....

**Comment by smeroni68** [comment]
Sorry, but this is normal when instead of a stock Samsung kernel you use a custom rom and kernel!!
This means that you never used before today a custom kernel.
