### ISSUE TITLE
Bluetooth Share Stoped

### ISSUE THREAD

**Issue by Zhaarr** [AOSP-JF-MM/issue_tracking_aosp#115]
A pop-up message keeps appearing

"Bluetooth Share Has Stopped"

Even if Bluetooth is off

**Comment by smeroni68** [comment]
When you report an issue, can you please detail what are you using? We do not have a chrystal ball to know what you have in your hands!

Phone version
Rom version and date
Baseband version
Gapps package and date

**Comment by Zhaarr** [comment]
Phone: Samsun Galaxy S4 GT I9505
Rom : ASOP 7.1.2 Version 20170716
Baseband Version: I9505XXUHPK2
Gapps : Arm 7.1 Aroma

The Bluetooth does not even come one at this point...

My bad for not giving details, I assumed that since I got here by clicking a link from Galaxy S4 form, that this was solely about the Galaxy S4.

Hope I can get my Bluetooth working soon.

Regards

**Comment by smeroni68** [comment]
Aosp issue tracker is shared between devices, so always are needed details. We support S4, MI5, OneplusX/2/3/3T.
Regarding the problem you found, is probably related to gapps aroma. 

Please, download the micro package and do a clean install to test.

**Comment by Zhaarr** [comment]
Hi,

I downloaded the micro package and did a clean install. But I still get the Bluetooth problem.

**Comment by smeroni68** [comment]
We can only tell you to do as this user has done:

https://forum.xda-developers.com/showpost.php?p=73140581&postcount=2695

Reflash dirty without any wipe the rom zip and reboot.

**Comment by Zhaarr** [comment]
Should I just reflash the Rom then, without any wipe...

**Comment by smeroni68** [comment]
Yes, I already wrote what you must try...

**Comment by Zhaarr** [comment]
Hi,

I did as you suggested, dirty flashed Rom.  Bluetooth is now working but the microphone does not work for skype. Should I open a new thread for that?

Thanks!

**Comment by smeroni68** [comment]
First, let's close this issue, than you can open another one... but if you don't get logs and link in the issue, is pretty unuseful and devs can't evaluate the problem... and the issue will be closed.
