### ISSUE TITLE
Errors I found... please fix 

### ISSUE THREAD

**Issue by maineUL** [AOSP-JF-MM/issue_tracking_aosp#118]
1.Bluetooth keep force closing......
2.No gallery to show my photos....
3.Storage promblem....some app can't write folder name or store data to SD card or internal storage..
4.can't get root access...
5. Battery status read different percentage at times....
6. Key button (back key)on device automatically keep going back when I have a app open....
7.please add back duration key light......

**Comment by smeroni68** [comment]
Hi, thanks for your report without any useful information. 
Do you think that without knowing your phone and all details we can answer your questions in any way different from the one I'm using?!
This area is not xda forum! 
Here it's needed to open an issue with information, logs of the issue and description on how to replicate it. 
Your list is good just for a forum!

I'll close this. If you want to reopen, provide all information required. 

CLOSE.
