### ISSUE TITLE
Microphone not working on S4 SPH-L720

### ISSUE THREAD

**Issue by ndkar1** [AOSP-JF-MM/issue_tracking_aosp#15]
Ok.  I have an S4 SPH-L720.  It was running 5.0.1 stock rooted.  I installed CWM recovery and everything worked perfectly.  I downloaded and installed the latest ROM from you guys, the correct Play Store, and the SU from you all.  Installed the ROM 1st, the store 2nd, and the SU app 3rd.  Everything works perfectly except my microphones.  No matter where I am in the ROM no microphone is ever detected.  I tried making phone calls, nothing.  I tried using Google Now, nothing.  I tried taking a video, nothing.  I'm wiping the phone and SD card and clearing the cache and dalvik cache and reinstalling the ROM now.  If I have the same issue, please tell me how to get whatever logs you may need to help me resolve the issue I'm having.  Thanks!

**Comment by FernBch** [comment]
What is the name of the zip you flashed? The date of the latest release is Dec 24. If you flashed that revert back. That build is for GSM variants only. The L720 is CDMA and the build for it is not ready.

**Comment by B--B** [comment]
Wrong zip, nothing to fix
