### ISSUE TITLE
Front Camera aspect ratio

### ISSUE THREAD

**Issue by rxclua** [AOSP-JF-MM/issue_tracking_aosp#19]
When using Messenger (facebook) or skype, the front camera aspect ratio is distorsioned.

**Comment by B--B** [comment]
Please try our latest release and let us know if works now, picture size has been fixed for stock camera, hopefully Messenger and Skype will work too!

**Comment by B--B** [comment]
No aswer, i suppose it's fixed, i close this bug, please reopen if it's not fixed
