### ISSUE TITLE
Can't Install on GT-I9508

### ISSUE THREAD

**Issue by zcgkiller** [AOSP-JF-MM/issue_tracking_aosp#20]
It displays "This package is for device: jflteatt,jfltecan,jfltetmo,jfltexx,jgedlte,jflte,i9505,GT-I9505,i9505g,GT-I9505G; this device is jfltezm" when I install the "AOSP-6.0-20151224-jfltegsm.zip" rom on my GT-I9508.
I checked the "update-script", I can't find my device type.
But in the xda thread, it said "support I9508".

**Comment by AntaresOne** [comment]
https://github.com/AOSP-JF-MM/platform_device_samsung_jfltegsm/commit/d33b706b2e92e5f82a020baa67ff7b57411ad145 added back
