### ISSUE TITLE
Phone unresponsive during and after call

### ISSUE THREAD

**Issue by SolGarlic** [AOSP-JF-MM/issue_tracking_aosp#24]
When during a call, the phone is unresponsivo: the proximity sensor or the home/power button don't turn on the screen.
Another simultaneous incomming call also doesn't turn the screen on and I cannot see who is calling me.
After the call ends I hear 3 long tones and after a few seconds I am able to turn on the phone, but only with a long press of the power button (menu button doesn't work).

**Comment by SolGarlic** [comment]
Also happens with baseband I9505XXUHOJ2
Might also happen with previous ROM version and with CM13

**Comment by smeroni68** [comment]
Hi,
can you read this post on xda and tell us if is the same issue?

http://forum.xda-developers.com/showpost.php?p=64591021&postcount=1336

Because the answer you can find on some posts after this one... thanks...

**Comment by smeroni68** [comment]
Here the important posts:

http://forum.xda-developers.com/showpost.php?p=64596511&postcount=1351

http://forum.xda-developers.com/showpost.php?p=64596850&postcount=1355

and the result:

http://forum.xda-developers.com/showpost.php?p=64609953&postcount=1376

... hope you can solve in the best way as the user confirmed!!

Regards

PS: After close the "issue"...

**Comment by SolGarlic** [comment]
Thanks.
Tried searching with "unresponsive" or freeze, but didn't find that post.

**Comment by plrodrigo** [comment]
http://repo.xposed.info/module/com.mrchandler.disableprox install this module xposed

**Comment by plrodrigo** [comment]
I advise Go to setting>accesibility and power on power button hangs

**Comment by plrodrigo** [comment]
I recommend you Go to setting>accesibility and power on power button hangs sorry for bad english
