### ISSUE TITLE
Wifi tethering only works on 2.4ghz band

### ISSUE THREAD

**Issue by kiwi32** [AOSP-JF-MM/issue_tracking_aosp#26]
Hi,just got it running on an SGH-i337M. When turning wifi hotspot on,it work if the selected AP band in the settings is 2.4,but if 5ghz is selected instead,it says "error" under the tethering toggle in the settings when trying to turn it on. Small bug but pretty annoying as I tether in crowded areas and 5ghz works better in those.

**Comment by B--B** [comment]
2.4 Ghz is actually the only option available on our ROMs, this report can be closed
