### ISSUE TITLE
Miscellanous Battery Drain

### ISSUE THREAD

**Issue by Empty2k12** [AOSP-JF-MM/issue_tracking_aosp#3]
On 5.1 this was related to NFC. Might be again! Great to see you back Antares!

**Comment by B--B** [comment]
No battery drainage in latest release, "various" in battery does not mean that the device is draining battery, it has beeen discussed a lot of times on xda.. My battery life is very good and i do not have any rogue app in my system or strange wakelock.. I close this bug, next time please post the required information and a log with the battery stats and the wakelock that cause the drainage
