### ISSUE TITLE
 IR REMOTE CONTROL

### ISSUE THREAD

**Issue by francquadros** [AOSP-JF-MM/issue_tracking_aosp#34]
Hello! It's not working the IR in my day installation 02.08.2016 , use the APK Intelligent Remote Control 3.4.0 on CM13 and TW is functioning normally , I tried the Peel Smart Remote , but also does not work , my S4 is the GT -I9505 , clean installation .

**Comment by B--B** [comment]
Please submit the report with all the requested and needed information, otherwise we won't be able to help you... BTW I've tested the IR with my TV and anymote and works for me with both drivers without any issue.

**Comment by francquadros** [comment]
I restored the data from BK Titanium , which had backups of apk 's
working in CM13 . always I made these restorations in all Rom's
already installed , always worked , I do it because it has several
parametric controls , but I'll try a clean install.

Franc Quadros

franc.quadros@gmail.com nfe@flapa.com.br

_Tel: +55 31 9668-6782_

_P_  _Antes_ de imprimir pense em seu compromisso

com o Meio Ambiente e o _comprometimento com os custos._

2016-02-11 15:12 GMT-02:00 B--B notifications@github.com:

**Comment by jonatasas10** [comment]
Thanks B--B for answering.

I activated and deactivated the USE PREVIOUS IR DRIVER in Toolbox  and it does not work the same way. I use the app PEEL SMART REMOTE and my TV is AOC (in JDC CM12.1 and AOSP 5.1 works normally).

What could be my problem?

Logs: https://mega.nz/#!vgUx0ZQC!eCSCbNHEOTCa_3pFEbMYjmaz7_z3XbpcTO0cEnTnHjQ

**Comment by B--B** [comment]
Please try Anymote, go to settings, UNCHECK "Use Alterante Ir Commands" and try if works with Anymote... I'm actually using with my 2 LCD and it's working fine without any issue

**Comment by jonatasas10** [comment]
Ok, in next build I'll try. Now, I'm on JDC AOSP 5.1.1 and works normally.

**Comment by jonatasas10** [comment]
I try and it works, but not works well. Have some issues. JDC CM13 the peel smart works well. 

My baseband is VJUHOK1 (a little old), if I upgrade may work better?

**Comment by jonatasas10** [comment]
Now, the anymote works well, thanks. 

I disabled the IR Driver in toolbox, and disabled the "IR alternative" in anymote and works well. Issue solved.

**Comment by B--B** [comment]
Good, more users reported on xda too that AnyMote works without issues, this can be closed
