### ISSUE TITLE
Calls problem

### ISSUE THREAD

**Issue by tyger1985** [AOSP-JF-MM/issue_tracking_aosp#38]
I have a problem, it doesn't happend every time.
When i receive a call i hear who's calling me but they cannot hear me, i must reboot the phone, after that they hear me. Every time it happened i was listening to music and answer from ears button.

I've updated Bootloader and Modem from I9505XXUHOL2 to I9505XXUHPA1. Still got that problem.

Phone model: GT-I9505
ROM version: 20160208
Gapps:  A-GAPPS 6.0.1 (minimal)
Did you do a clean install for the currently installed build? YES
Did you reboot after having the issue? YES
Did you do any system modification? NO
Did you flash another kernel? NO
Did you install Xposed framework? NO

Thank You!

Later edit: I've made some tests. Seems that if i accidentaly press 2 times on ears button to answer the call, the second time it turn off the microphone. If i end call, and try to call again, the microphone shows its enabled but other person can't hear me. If i disable and reenable the microphone, everything it's ok.  So, the answer button from ears does not close the call, it's turn off/on microphone.

**Comment by FernBch** [comment]
A logcat is really needed to help with this issue.
