### ISSUE TITLE
Wifi direct

### ISSUE THREAD

**Issue by tyger1985** [AOSP-JF-MM/issue_tracking_aosp#39]
Wifi direct doesn't work to send or receive files. I am able to connect to other device but nothing more. Tried with 2 Samsung S4, an S6 edge+ and Motorola Nexus 6 none works. I don't know what logs to attach. Seems other people have same problem ( http://forum.xda-developers.com/showpost.php?p=65432483&postcount=3253 )

Phone model: GT-I9505
•Baseband version: I9505XXUHPA1
ROM version: 20160208
•GApps Package:  A-GAPPS 6.0.1 (minimal)
•Did you do a clean install for the currently installed build? yes
•Did you reboot after having the issue? yes
•Did you do any system modification? no
•Did you flash another kernel? no
•Did you install Xposed framework? no

Thank You.

**Comment by B--B** [comment]
I've tried now and I successfully transferred a file using wifi direct at 5 Mb/s, I've connected the devices and used es file explorer  for the share, everything works for me, please provide us a log or we can't help you

**Comment by tyger1985** [comment]
I install Es File Explorer and not succed. I've made some screenshoots.
![screenshot_20160221-165731](https://cloud.githubusercontent.com/assets/17331805/13203287/94519b56-d8bd-11e5-85b6-184f34b587b5.png)
![screenshot_20160221-165641](https://cloud.githubusercontent.com/assets/17331805/13203289/9f0a3b2a-d8bd-11e5-9546-7601fe8a1e35.png)
![screenshot_20160221-170134](https://cloud.githubusercontent.com/assets/17331805/13203294/a5dcde62-d8bd-11e5-841b-41a3630f56b8.png)
![screenshot_20160221-165954](https://cloud.githubusercontent.com/assets/17331805/13203296/ad74895e-d8bd-11e5-87b6-d6c74851b4d5.png)

I tried create a network still failed.

**Comment by FernBch** [comment]
Logcats are what is needed so the developers can see what is happening.

**Comment by B--B** [comment]
As i previously said, it's working for me: 
![screenshot_20160221-160042](https://cloud.githubusercontent.com/assets/7747806/13203755/bdb75c46-d8be-11e5-8e25-2d65da477e72.png)

![screenshot_20160221-160413](https://cloud.githubusercontent.com/assets/7747806/13203756/c6c5f3f6-d8be-11e5-89e1-3bf024d8608b.png)

![screenshot_20160221-160425](https://cloud.githubusercontent.com/assets/7747806/13203757/ce21c508-d8be-11e5-986b-f91d456e867d.png)

Please provide us a log of the issue, because for me it's fine..

**Comment by tyger1985** [comment]
Sorry, i didn't know what logs do you need. I install SysLog and i attatch the zip
https://mega.nz/#!DBlXWYbJ!AJ5Au6o8Kw6-b3nybrO7T714mNpui0-74xWhO79cscs

**Comment by B--B** [comment]
Tested again, wifi direct works fine for me, this can be closed
