### ISSUE TITLE
bluetooth doesnt work

### ISSUE THREAD

**Issue by coolmisty45** [AOSP-JF-MM/issue_tracking_aosp#4]
The blue tooth crashing when i try to pair devices
Phone: l720/l720t

**Comment by bobwonderful** [comment]
I have L720 and it pairs properly for me.  I have paired to my motorola Roadster2, my Jawbone ERA and my Jawbone Jambox as well. When you installed 6.0 did you do a clean install including formatting the data partition and system partition as well as the cache and Davlik cache?

**Comment by B--B** [comment]
Pair issue fixed with latest release, bt has been completel reworked, this bug can be closed
