### ISSUE TITLE
5ghz WIFI not working M919

### ISSUE THREAD

**Issue by ke4clu** [AOSP-JF-MM/issue_tracking_aosp#40]
FYI

I see you closed the issue on the no 5ghz wifi.  I installed this ROM yesterday (2/23/16) and have the same issue with not being able to see any 5ghz AP .   I had a problem with bluetooth as well.   Bluetooth would pair with my m919 and function as it should but,  when I paired it with my Eonon headunit, I had no phone service.   The 5ghz was not a deal breaker for me but the bluetooth issue was.

For testing I installed and am still using JFLTE-GPE-20151021.zip from http://forum.xda-developers.com/showthread.php?t=2557353.    JFLTE-GPE-20151021.zip ROM fix both issues for me.

It was mention that the Baseband version may be the issue.    Well  your Marshmallow ROM and the GPE ROM I am using now both have baseband V M919UVUFOH3.   So it seems that isn't the issue.

```
Phone model: SCH-M919
Baseband version: M919UVUFOH3
ROM version: AOSP-6.0-20160208-jflte.zip


GApps Package: CM GApps [date] or Open GApps [type] [date] or Slim GApps [type] [date] ex.  Open GApps Full 

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? yes: stock kernel available on RomHut
Did you install Xposed framework? no
```

**Comment by smeroni68** [comment]
You wrote you are using both roms... but are you using Multirom?

If yes, witch is the primary rom?

**Comment by ke4clu** [comment]
No I'm not using multi Rom whatever that is..  I have wiped the system and reinstalled JFLTE-GPE-20151021.zip.   I have tried several of the Marshmallow ROMS with the same result.  eg. CM13, Resurrection remix, VRToxin,  AOSP from Team Android.
