### ISSUE TITLE
Microphone problem

### ISSUE THREAD

**Issue by pappapjotor** [AOSP-JF-MM/issue_tracking_aosp#41]
Since I updated to feb 8th build, people can barely hear me.
Calls made through whatsapp, messenger etc is fine, it's only regular calls that are affected.
Phone model: GT-I9505
Baseband version: I9505XXUHPA1
ROM version: 20160208
GApps Package:Open GApps Mini 20160228

Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no
[2016-02-24_15.28.zip](https://github.com/AOSP-JF-MM/issue_tracking_aosp/files/144764/2016-02-24_15.28.zip)

**Comment by pappapjotor** [comment]
So, now I've updated to HPA1 baseband.
When on 5.01 i tried to make a call, and it was just fine. But when 6.0.1 installed it's the same problem again.

**Comment by B--B** [comment]
This can be closed, we switched to the new audio HAL and mic volumes now are good

More info here: https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/commit/ae82ad571afc62a74ca0b86b7f6e3dd8b63489a0
