### ISSUE TITLE
LTE/3G/2G

### ISSUE THREAD

**Issue by raczrichardd** [AOSP-JF-MM/issue_tracking_aosp#42]
Cannot switch between LTE/3G/2G. Nothing happens when I turn off mobile data or using wifi. Another problem is when I use wifi my data usage is increases a few megabytes per a day. I hope you will fix it soon. Thanks

**Comment by B--B** [comment]
Provide all requested info and i will reopen this bug, this is not the right way to report an issue... BTW it should be fixed and working for all variants

FYI: your phone connects several time to cellular data in various situations even if you are connected to wifi (IE when location is enabled), so it's normal
