### ISSUE TITLE
Bluetooth audio: error playing next song

### ISSUE THREAD

**Issue by paolo2331** [AOSP-JF-MM/issue_tracking_aosp#43]
here is the link to the log 
[https://www.dropbox.com/s/jwuvrd622xogl4s/Log_2016-02-26_14-28-37.txt?dl=0](url)

The problem is around at 14:00 - 14:30 of 27/02

When I connect to Uconnect car kit music streaming has some problems.. if i push the button to change song, the error occurs and I can't play anymore any songs even choosing from the phone.

**Comment by paolo2331** [comment]
Phone model: GT-I9505
Baseband version: ex. I9505XXUHOJ2
ROM version: 20160208
GApps Package: Open GApps Nano 20160211 
Did you do a clean install for the currently installed build? yes 

Did you reboot after having the issue? no
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

**Comment by B--B** [comment]
Duplicated of https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/30
