### ISSUE TITLE
Low microphone volume

### ISSUE THREAD

**Issue by coolpix90** [AOSP-JF-MM/issue_tracking_aosp#44]
I've low microphone volume recording audio message ( whatsapp and others ). I'm trying to make a log but with no success. I tried to solve with stweaks but it has no effects.

**Comment by B--B** [comment]
This can be closed, we switched to the new audio HAL and mic volumes now are good

More info here: https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/commit/ae82ad571afc62a74ca0b86b7f6e3dd8b63489a0
