### ISSUE TITLE
"Sim Card Removed" Must restart phone.

### ISSUE THREAD

**Issue by codeseven58** [AOSP-JF-MM/issue_tracking_aosp#45]
It's been occurring for quite some time. today it happened 4 times. When I first installed the 20160208 release, it was happening up to 8 times/day. After wiping cache and reinstalling enough times it stopped. but something happened and it began occurring again recently. In this file I had a "sim card removed" problem, restarted my phone, and had the error appear within minutes. 
[2016-03-03-17-59-33.txt](https://github.com/AOSP-JF-MM/issue_tracking_aosp/files/158086/2016-03-03-17-59-33.txt)

**Comment by codeseven58** [comment]
Performing complete wipe and starting over. Wiping Dalvic/Art Cache, Cache, Data, Internal Storage, Preload, and System.

**Comment by codeseven58** [comment]
Issue persists after complete wipe.
https://drive.google.com/file/d/0B92I26nDotirUkZMMFdGa3MtRVk/view?usp=docslist_api

**Comment by codeseven58** [comment]
Phone model: SGH-M919
Baseband version: m919uvufok3
ROM version: 20160208
GApps Package: opengapps pico 20160208

Did you do a clean install for the currently installed build? yes and no

Did you reboot after having the issue? yes, no choice.
Did you do any system modification? yes: x-posed with no-charging-light mod. also occured without xposed installed and a clean wipe.
Did you flash another kernel? no
Did you install Xposed framework? yes and no

**Comment by javelinanddart** [comment]
Have you tried updating your modem to one that's post JB?
It could also be a hw issue

**Comment by smeroni68** [comment]
I suggesto to do a clean flash of another rom that has worked for you before and check if the problem disappear... it's the best way to diagnose if is an hw problem.

**Comment by codeseven58** [comment]
Not a hardware issue, not present in stock firmware.

And I haven't found another rom that is worthy of trying out :-\

However I may have found a solution. I went in and reset the APNs to default via the menu at the top right in the cellular network section. I haven't had an issue since. Although, i just realized doing this also defaulted my APN to brightspot, which is what I've been using for the past day. Im going to set it back to T-Mobile LTE and see if it starts to happen again.

**Comment by codeseven58** [comment]
Update, after realizing I was on the brightspot APN and switching back to t-mobile LTE, i got another "sim card removed" error 24 hours later.

_edit_

Updating APN settings to those on t-mobile's website  to test for errors.
https://support.t-mobile.com/docs/DOC-5881

_2nd edit_

lasted 2 hours before I got another "sim card removed" error

**Comment by codeseven58** [comment]
2 days since last "sim card removed" error. restting APNs to default and defaulting to brightspot seems to have fixed the issue. also wiped dalvik after swapping.

**Comment by codeseven58** [comment]
3 days no error.... will post next reply either when i get an error or after a week

**Comment by codeseven58** [comment]
more errors started sprouting for unknown reasons. resetting APNs wasn't an appropriate solution. perhaps this can point someone in the right direction?

**Comment by AntaresOne** [comment]
@codeseven58 Still experiencing that issue? First make sure the SIM card is fine. If so, your SIM card module needs to be changed. It's relatively easy to do it and you could save up a lot of money by repairing yourself. Try to search "I9505 SIM card reader" on eBay or Amazon, this spare part is the same for any S4 LTE

**Comment by codeseven58** [comment]
I'm sorry AntaresOne. After enough errors I followed the instructions [here ](http://forum.xda-developers.com/galaxy-s4-att/general/how-to-fix-galaxy-s4-sim-card-removed-t3113480)and have not had an error since. I guess the Issue is hardware related. More specifically, the connector doesn't make good contact either after some time or after being dropped so many times. Thank you for your time!
