### ISSUE TITLE
No audio recorded in most apps

### ISSUE THREAD

**Issue by asfaltboy** [AOSP-JF-MM/issue_tracking_aosp#5]
It seems that all applications except the phone app capture no audio. Some applications (skype, hangouts) request the permission to record audio, but even after allowing those nothing is recorded.

Not sure which logs to provide here, here are my details:

Phone model: **GT-I9505**
Baseband version: **I9505XXUEML1**
ROM version: **20151108**
GApps Package: **gapps marshmallow mini ([from the instructions](https://romhut.com/addons/gapps-mm-mini-93670cb6-84d5-4dc2-ba9f-62b1e1865444))**

Did you do a clean install for the currently installed build? **yes**
Did you reboot after having the issue? **yes**
Did you do any system modification? **no**
Did you flash another kernel? **no**
Did you install Xposed framework? **no**

**Comment by B--B** [comment]
Fixed with this commit: https://github.com/AOSP-JF-MM/platform_frameworks_av/commit/91531d12a1f6b4546abdbf96a2fc81d6583e3eb7

**Comment by asfaltboy** [comment]
Thanks @arco. I wonder, do you guys have a automated build flow that produces a ROM image for every commit merged to master? IOW is there an easy way to get a version to test resolution?

**Comment by arco** [comment]
Hey,

Not that I know of, but I think we can initiate a build manually. I build and test locally though. Normally a full build isn't needed, but just the component you want to test, by pushing it to the device and rebooting.

Edit: I was talking about CM though. :)

**Comment by asfaltboy** [comment]
Thanks! Is there a guide you could point me to, in order to understand the build steps of specific AOSP-JF-MM component (I assume such as [platform_frameworks_av](https://github.com/AOSP-JF-MM/platform_frameworks_av))?

**Comment by javelinanddart** [comment]
You'd first have to understand building a ROM fully from source

**Comment by lazyw0lf** [comment]
Having the same problem: "It seems that all applications except the phone app capture no audio."
I saw that @arco fixed the problem 3 days ago in his commit.. I'm not able to build myself the rom for testing it any tips and tricks for noobs? ;) thanks in advance. 

Phone model: GT-I9505
Baseband version: I9505XXUDMGG
ROM version: 13.0-20151108-UNOFFICIAL-jflte
GApps Package: open_gapps-arm-6.0-full-20151113
Did you do a clean install for the currently installed build? yes
Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? yes

**Comment by javelinanddart** [comment]
1. Don't used Xposed
2. If you look on XDA there are plenty of guides on how to build a ROM

**Comment by lazyw0lf** [comment]
I've installed xposed after having flashed the rom for the second time and saw if the microphone problem was still existing. So xposed changes nothing for this problem..

**Comment by asfaltboy** [comment]
I can confirm that latest From (6th Dec) solves the issue



Best regards,
Pavel Savchenko

**Comment by lazyw0lf** [comment]
Ok I saw now that they published the latest build on 6th December! Thanks a lot! ;)

**Comment by asfaltboy** [comment]
I can confirm that the latest ROM ([from 6th Dec](http://forum.xda-developers.com/showpost.php?p=64178560&postcount=407)) resolves the issue.

**Comment by lazyw0lf** [comment]
The microphone fix it's working for me too!! =D really great job! very smooth animation and other cool stuff! 
I just can't understand one thing, I can't find the theme chooser app but instead I've found Layers Manager app that it's a little bit laggy and I can't remove the theme I've applied. 

I've installed "open_gapps-arm-6.0-full-20151208" and I see some other apps like message, file explorer and browser (material design I've found on the first cm13) are disappeared.

**Comment by smeroni68** [comment]
On AOSP there is no Theme Engine (CM), but Layer Manager with RRO layers.
Layer Manager let you use also different combinations of layers from different packages. Until now, the removing of layers is not working, probably for a permission on folders. If you want remove them or some of them, you can go with a root explorer on root folder on vendor/overlay, mount ar R/W and delete manually the layer files (just remember to soft reboot after deleting.
If you update the rom, overlays are automatically deleted and you must re-apply.

**Comment by lazyw0lf** [comment]
Thanks you a lot man!!! 😉 you've saved me.. It worked fine and after reboot everything was on stock theme! 👍
