### ISSUE TITLE
No cellular data connection for SPH-L720

### ISSUE THREAD

**Issue by david2012brooke** [AOSP-JF-MM/issue_tracking_aosp#51]
I'm having trouble with the cellular data connection using the 20160314 - Beta 6. It isn't working at all.
I checked all the cellular settings and saw that I didn't have an APN list / page. Also I noticed I get this message:
Settings>More>Mobile plan>"Please insert SIM card and restart". I don't get this message on other rom's (including JDC Lollipop's) or stock KitKat and Lollipop. Also the APN listing for Ting has been removed from the APN config xml file (which is my carrier). Here is the APN info I think that should work:
apn carrier="Ting" mcc="310" mnc="120" apn="n.t8.ispsn" type="default,mms" mmsc="http://mms.plspictures.com" mmsproxy="68.28.31.7" mmsport="80" protocol="IPV4V6" roaming_protocol="IPV4V6"
I can make calls and text via the cellular connection.
I can text and MMS via wifi.
But I can't use the browser or MMS via the cellular connection.

I found that this code _#_#4636#_#_
Allows you to evaluate / test the available networks. I was able to test each network for cellular data capability while using the JDC MM rom. The following results, indicated by yes or no, tell whether data works:
WCDMA - NO
GSM ONLY - NO
WCDMA ONLY - NO
GSM AUTO (PRL) - NO
CDMA AUTO (PRL) - YES 3G
CDMA ONLY - YES 1X
EXDO ONLY - NO
GSM/CDMA AUTO (PRL) - YES 3G
LTE/CDMA AUTO (PRL) - NO
LTE/GSM AUTO (PRL) - NO
LTE/GSM/CDMA AUTO (PRL) - NO
LTE ONLY - NO
UNKNOWN - NO

Default selection after reboot = LTE/CDMA AUTO (PRL)
I can manually switch to either CDMA AUTO (PRL) or GSM/CDMA AUTO (PRL) and cellular data will work until the next reboot.

Let me know what other info you made need.

**Comment by B--B** [comment]
This issue belongs to MM, but next release will be the last, so i close this as MM reached the EOL, N is our stable release now, and unfortunately i have no time to keep two different ROMs alive for multiple devices, BTW with N stable and bug free (wifi hotspot will be fixed in next upcoming release) i don't see the sense to stay with an older android release and OMS working only in legacy mode
