### ISSUE TITLE
NOT AN ISSUE.JUST QUESTION

### ISSUE THREAD

**Issue by dkati** [AOSP-JF-MM/issue_tracking_aosp#53]
hello :)
any ideas of why cant switch network type ?

thats from adb

NetworkSettings: handleSetPreferredNetworkTypeResponse: exception in setting network mode.

thanks

**Comment by B--B** [comment]
Hi, sorry for being late but i'm really busy in these days...! But are you referring to our cm? In that case i've fixed the network switch yesterday, see here: https://github.com/JDCTeam/android_frameworks_opt_telephony/commit/eb30f80d249d8df9704d2593f7406f075e7354c7
I've merged all latest cm changes, solved all conflicts and fixed upstream merge option in our script, now we can use the build script for merge all the code without the need of picking a single commit everytime..!

**Comment by dkati** [comment]
thanks for that :/ 
was too ''deep'' for me..

**Comment by B--B** [comment]
I think that i can close this now..! :-)
