### ISSUE TITLE
Missing icons in snapdragon camera

### ISSUE THREAD

**Issue by paolo2331** [AOSP-JF-MM/issue_tracking_aosp#59]
Just a minor issue: the icons inside snapdragon camera disappear when device turns in landscape mode.

Thanks again for you work!

**Comment by B--B** [comment]
Hi, icons and focus function has already been fixed in our internal builds, i' ve pushed all the changes yesterday and a few minutes ago...!

**Comment by paolo2331** [comment]
Many thanks! Have a nice weekend
