### ISSUE TITLE
Can't skip/play/stop music track with headset button

### ISSUE THREAD

**Issue by andreiciocanvlad** [AOSP-JF-MM/issue_tracking_aosp#62]
With Pico Gapps

The phone is not displaying headset connected icon and i can't start, pause or skip tracks. I enabled auto-start media player when headset connected, this works, but still no control with button.

**Comment by B--B** [comment]
Logs? Build? More info?
PS: i do not see any option for auto-start media player when headset connected, i haven't ported the feature from cm..

**Comment by andreiciocanvlad** [comment]
Auto start of music player is in settings - sounds

**Comment by smeroni68** [comment]
Sorry... but you are on AOSP bug tracker... this feature is in CM code not in AOSP... wrong place.
