### ISSUE TITLE
Bluetooth 4.0 LE not working

### ISSUE THREAD

**Issue by bestsase** [AOSP-JF-MM/issue_tracking_aosp#64]
I am not able to pair and connect with my Mi Band 1s...
than noticed that i can't connect to my Nexus 7 either, it Pairs with it but not connecting...

Phone: I9505

**Comment by B--B** [comment]
Latest public build? In that case wait the latest public build and let us know if works. i've completely reworked the bt repos, now code is synced with cm, if works on our opt-cm-13.0 then should work fine here too!

**Comment by bestsase** [comment]
20160416 version, so ye probably its latest.. Also yes in cm13 it works okay, but not on aosp :(

**Comment by georgiptr** [comment]
I confirm that I also can't pair the phone with my Xiaomi Band 1S using Stable 1 from 2016/04/16.

**Comment by JoyMachine** [comment]
Same here... I have tried to connect Polar H7. It just trying to pair and after 30s it stops.
On CM-13-20160510 it connects in a few seconds.

**Comment by B--B** [comment]
I close this bug cause i synced my bt branches with cm, now everything works like in cm and people reported on xda that this issue is gone
