### ISSUE TITLE
Process android.process.media stoped when change USB option to MTP

### ISSUE THREAD

**Issue by timerons** [AOSP-JF-MM/issue_tracking_aosp#66]
hi,
i just installed the latest version on a clean s4. everything works fine. when i connect the device with my win 10, the usb setting is set to charge battery, when i change to MTP i a pop up that says the process android.process.media was stopped.
[Log_2016-05-05_20-54-10.txt](https://github.com/AOSP-JF-MM/issue_tracking_aosp/files/251016/Log_2016-05-05_20-54-10.txt)

after a 30sec i see my device on the windows side. (it seems to me that this is unusual long)

if you need any other information, let me know. i do not use the F2FS.

timerons

**Comment by B--B** [comment]
Duplicated of https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/74, i close this bug, we continue the discussion there
