### ISSUE TITLE
Can't Access External SD card, nor any data when connected to USB cable and Windows 10 computer

### ISSUE THREAD

**Issue by PastorB** [AOSP-JF-MM/issue_tracking_aosp#68]
Well, I'll leave this post as an open example of the fact that people (particularly me!) should install the latest build before reporting bugs!  I downloaded the most recent version (apparently I had an older version) and found that I can now access the external SD card.  

Alas, I when I hook the phone up to my computer I still can't get a connection to the computer, to see any data, either on the internal storage or the external SD Card, but, the work is progressing!

Friends,

I just installed your Android 6.0 ROM on my Sprint Galaxy S4 phone.

The Build # is aosp_jflte-userdebug 6.0 MRA58V eng.b-b, 20151107.191059 test-keys.

The Kernel version is 
3.4.107-aosp-gd807cc4 
antaresone@Asus-N551.JX#1
Wed Nov 4 02:05:25 CET 2015

I have an 8 GB SD card installed.  When I go to settings and Storage I can see the SD card and access the files (or at least click and read text or view a picture).  However, when I try to access the SD card using Solid Explorer it does not even see that a SD card is installed.  Then when I connect the phone to a USB cable and then to my Windows 10 computer, a window pops up showing the phone, but with nothing visible, no internal or SD storage.

I had a 32 GB card in the phone and it came back and said that the card had to be formatted.  I had assumed that and had already taken all needed off the card.  When I told it to go ahead and format the card it began the format, the indicator said 20% and then in less than 20 seconds it said that the format was finished.  Nothing visible, no data, no card.  When I took that card and put it in another phone the card is blank except for "LOST.DIR" and "Android" (the Android folder containing a data folder with some other folders in it),  I think these were created when I put the card in the new phone, but I'm not sure.  When going to Device storage the SD card shows up, but with a red/orange triangle and an exclamation point in it next to it.

I'm sorry, but I don't know how to send you any error logs.  If you tell me how I'll be happy to do it.

The USB is configured for Media Transfer Protocol (MTP), and USB debugging is enabled.

Thanks for what you are doing!.

Michael

**Comment by B--B** [comment]
Fixed, this report can be closed
