### ISSUE TITLE
BT-Share FC

### ISSUE THREAD

**Issue by AgentDale** [AOSP-JF-MM/issue_tracking_aosp#69]
SGH-I337M
Gapps Package: Open Gapps Stock

Did you do a clean install for the currently installed build? Yes
Did you reboot after having the issue? Yes
Did you do any system modification? no
Did you flash another kernel? No, on alucard
Did you install Xposed framework? No

With the latest build (4-16, Stable 1) after 30 minutes connected to my smartwatch, I receive a BT Share has stopped message, and bluetooth crashes. It doesn't come back on until I restart. Gas Buddy is not installed, and I have ruled out third party apps causing this problem.

**Comment by tonivdv** [comment]
👍

**Comment by B--B** [comment]
No one reported Bt share crash in our latest releases, i close this report as a lot of time has passed, if happens again open a new report with logs, thanks
