### ISSUE TITLE
[Very Low Priority] Bluetooth audio stopped streaming. Did not crash.

### ISSUE THREAD

**Issue by codeseven58** [AOSP-JF-MM/issue_tracking_aosp#71]
Phone model: SGH-M919 JFLTETMO
Baseband version: m919uvufok3
ROM version: 2016-05-24
GApps Package: open gapps arm 6.0 pico 20160524

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? no. issue was solved by turning music player and bluetooth off then on. music resumed running error free.
Did you do any system modification? adaway?
Did you flash another kernel? yes 3.4.111-Alucard -PWR-CORE - b--b@JDCTeam #29 - 2016/04/15
Did you install Xposed framework? no

Hey guys, I experienced a bluetooth bug that ive never experienced or heard of before. I got in my vehicle today and began listening to music via bluetooth. I then made a call and hung up, listened to music without problems, made another call and hung up, and my phone stopped streaming music audio. Turning bluetooth and my music player off and back on fixed the issue. Here is an error catlog. http://pastebin.com/YurQNz47.

**Comment by B--B** [comment]
Our testers reported that latest kernel changes and the new audio HAL fixes this issue, so this can be closed 

Related bugs:
https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/73
https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/30
https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/61
