### ISSUE TITLE
Android.Process.Media has stopped.

### ISSUE THREAD

**Issue by codeseven58** [AOSP-JF-MM/issue_tracking_aosp#72]
Phone model: SGH-M919 JFLTETMO
Baseband version: m919uvufok3
ROM version: 2016-05-24
GApps Package: open gapps arm 6.0 pico 20160524

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? no.
Did you do any system modification? no
Did you flash another kernel? yes 3.4.111-Alucard -PWR-CORE - b--b@JDCTeam #29 - 2016/04/15
Did you install Xposed framework? no

Whenever I plug my phone in to my computer, and select either file transfer or media transfer, I get a message saying that android.process.media has stopped. i usually only see it on my personal test builds though. not sure if it's even relevant. 

Error log:
http://pastebin.com/raw/Bp0sTmhA

**Comment by B--B** [comment]
I close this cause it's duplicated of https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/74
