### ISSUE TITLE
android.process.media has stopped

### ISSUE THREAD

**Issue by Stoyan81** [AOSP-JF-MM/issue_tracking_aosp#75]
Phone model: GT-I9505
Baseband version: I9505XXUHOJ4
ROM version: 20160612
GApps Package: Open GApps Nano 20160612

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? no
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

Exactly the same problem (as the codeseven58) connecting to USB. Even in Developer options and choose MTP when connect USB cable again appears "android.process.media has stopped". After several restarting I was able to connect via USB, but now freezes on "DevConnection" and can not start normally.

**Comment by B--B** [comment]
Duplicated of https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/74 , if you are in latest public release then you have this problem, i already posted in other issue the possible fix, our testers are trying it and no one experienced media crash until now
