### ISSUE TITLE
No root access for stweaks and jdc toolbox

### ISSUE THREAD

**Issue by FPSUsername** [AOSP-JF-MM/issue_tracking_aosp#78]
Hello,

Since stable 1 I unrooted and forced systemless root (v2.74). When I open Stweaks I get the timeout/no root issue. JDC Toolbox also doesn't ask for root. Other apps like root explorer ask for root access and works fine.
Busybox is still installed, v1.25.0 dorimanx.
I'm already on stable 3 and still don't get the root access I need for stweaks.

**Comment by B--B** [comment]
Hi, some errors in logs?

**Comment by FPSUsername** [comment]
http://pastebin.com/yhmzR6Jv Here is a log
Btw, I use systemless xposed, with or without, still not working, same goes for wiped system and caches.

**Comment by B--B** [comment]
Fixed, this report can be closed
