### ISSUE TITLE
OTA Updates shows null and does not update

### ISSUE THREAD

**Issue by timerons** [AOSP-JF-MM/issue_tracking_aosp#82]
In the OTA Updates app it says on the top:
"Aktualisierung verfügbar" (Update available)
"null"
"Antippen um Download zu starten" (Press to start download)

In the windows below is see
ROM-Information
ROM name:AOSP-JF-6.0
ROM version: 20160416
Datum: sab 16 apr 2016, 14.29.56 CEST
Android-Version: 6.0.1

When i click on download i see on the screen
null
0B (at right side)
MD5: N/A (at right side)
null (at right side)
null (at the left side)

at the bottom i can click only in "Heruterladen" (Download)
if i do that, i see 
"OTA Updates" wurde beendet (was stoped)

**Comment by smeroni68** [comment]
If you read the OP on XDA (first post of the thread), you have the answer...

http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/jdcteam-android-source-project-mra58v-t3251663
