### ISSUE TITLE
Notification stops working after whatsapp call

### ISSUE THREAD

**Issue by zabihchaudhry** [AOSP-JF-MM/issue_tracking_aosp#86]
Whenever i receive call from facebook or whatsapp then my notification stops working except vibration. Always had to restart. Please fix it.

**Comment by FernBch** [comment]
Clean flash or dirty?

A log would be needed here. Without it one can only guess at a possible cause.

**Comment by zabihchaudhry** [comment]
Clean install... How can i show you the logs

**Comment by FernBch** [comment]
Install an app such as logcat extreme, catlog, syslog, etc. from Play, on first use enable SU access, and save the log. The steps to save vary depending in which app you install but it is quite easy. Once saved upload it to Dropbox, Pastebin, etc. and then post the link to the log here.

**Comment by zabihchaudhry** [comment]
Thats my link for log:
https://www.dropbox.com/s/hyktqu7dzs75rvy/Log_2016-07-31_05-37-47.txt?dl=0

**Comment by B--B** [comment]
Fixed, this report can be closed
