### ISSUE TITLE
Gallery crashes when refused permission to location.

### ISSUE THREAD

**Issue by codeseven58** [AOSP-JF-MM/issue_tracking_aosp#88]
Like the title says. I don't want anybody to know my location, especially if they're trying to force me to give them access. Also, I know this isn't a bug as per BB [here](http://forum.xda-developers.com/showpost.php?p=68759655&postcount=7138).

http://pastebin.com/sb2QTHCC

**Comment by B--B** [comment]
Gallery needs the permission for show on map option (geotag), if I remove the permission check gallery opens, then you'll get a security exception when trying to use show on map feature... Don't think it's a good idea remove the check and let gallery open

**Comment by codeseven58** [comment]
I hate it when companies "force" you to let them have their way. I ended up reverting to the 08/12 build since it doesn't do that crap. The odd thing is, that Maps was doing the same thing for a while, then after 1 update, it just stopped FCing when I hit deny.

**Comment by codeseven58** [comment]
Is there any way to disable gallery's new "show on map" option? I don't want to allow any app to access my location? except for maps for directions.
