### ISSUE TITLE
Accelerometer not working

### ISSUE THREAD

**Issue by terraniux19** [AOSP-JF-MM/issue_tracking_aosp#91]
I have this problem while playing games that use the accelerometer or while rotating the screen and it doesn't work. I tried also check the sensor in Sensor Test app and it doesn't show anything. This is Stable7 build for the S4 i9505

**Comment by B--B** [comment]
Tried just now with both jflte and mi5 with accelerometer analyzer and it's working fine for me, rotation works too without any issue

**Comment by terraniux19** [comment]
@B--B Ok, maybe I'll try the app you mentioned.

**Comment by terraniux19** [comment]
I tried the app and it isn't giving me any inofrmation about accelerometer. It seems to be broken.

**Comment by terraniux19** [comment]
Ok, that a little weird, but everything came back to normal when I restarted the phone.

**Comment by smeroni68** [comment]
Maybe next time you can reboot and check a second time before opening  an issue! Thanks.

**Comment by terraniux19** [comment]
Ok, now the sensor stopped working after a while. So my conclusion is that the sensor is broken. I think I need to give for repair.
