### ISSUE TITLE
My Samsung s4 gets very hot

### ISSUE THREAD

**Issue by shamas16** [AOSP-JF-MM/issue_tracking_aosp#93]
Just updated to android 7.0 and after few weeks it started to heat up. Especially when I charge it or play a 60 FPS video. Before I could do everything and it wouldn't go above 20°c but now it reaches 39°c with 100℅ process. One more thing I cannot seem to get into stweaks so I could change the settings. It says no root... But it doesn't ask me for granted access. Can you help?

**Comment by style2345** [comment]
S4 I9500 has Octa Exynos CPU and Has Heating Issue , 
I9500 & I9505 these s4 model only support 1080p @ 30fps not 60fps may be one of heating reason
Try to Flash Latest Official Lollipop Firmware & Then Flash 7.0 Rom , Observbe & Report


Thanks

**Comment by javelinanddart** [comment]
@style2345: We don't support I9500.
