### ISSUE TITLE
Network & Signals Drops So Many Times 

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#95]
Network & Signal Drops So Many Times in Xiaomi Mi5 

Affected Rom version & Device

ROM Version = [JDCTeam][7.1.1][12 March] 20170312 - Stable 2

Device = Xiaomi Mi5

**Comment by B--B** [comment]
Please try this kernel and report if disconnection issues are fixed: https://www.dropbox.com/s/ojq3jrkvitsaj9c/boot.img?dl=0

**Comment by style2345** [comment]
There is no disconnection but network & signal drop so many times which causes slow Internet on jio 4G and also voice calls are affected

**Comment by B--B** [comment]
Invalid for the same reason of all other issues reported, provide the requested info, thanks

**Comment by B--B** [comment]
No info provided after a month, closed.
