### ISSUE TITLE
JDC Team Nougat 7.1 Galaxy S4 Black screen during calls

### ISSUE THREAD

**Issue by winnieduhpoooh** [AOSP-JF-MM/issue_tracking_aosp#96]
Whenever I pick up a call, the screen happens to be left black due to the sensors. I would like to know if there's a fix for this.

**Comment by B--B** [comment]
I close this as it's a duplicated of https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/24 and has been discussed a lot of time here and on xda thread, and it's not a ROM related issue
