### ISSUE TITLE
Sometimes  little white  dot Showing on Display

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#97]
Some time a litte white shiny led like dot showing on the upper  left corner of screen of xiaomi mi 5

Affectes Version & Device

ROM Version = 

1] [JDCTeam][7.1.1][12 March] 20170312-        Stable 2.
2] [JDCTeam][7.1.1][28 March][Substratum][EAS] - Stable 3

Device = Xiaomi Mi5

**Comment by B--B** [comment]
This report is invalid (and not reproducible, at least by me) provide the requested info for a bug report

**Comment by B--B** [comment]
No info provided after a month, closed.
