### ISSUE TITLE
Most of time no call display only Ringtone play

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#98]
Most of time in xiaomi mi5  there is no call display only ringtone play , if we want to receive call or see call the have to enter pin lock & unlock screen & then slide notification bar & then have to click on call..

Affectes Version & Device

ROM Version =

1] [JDCTeam][7.1.1][12 March] 20170312- Stable 2.
2] [JDCTeam][7.1.1][28 March][Substratum][EAS] - Stable 3

Device = Xiaomi Mi5

**Comment by B--B** [comment]
This report is invalid (and not reproducible, at least by me) provide the requested info for a bug report

**Comment by B--B** [comment]
No info provided after a month, closed.
